service: meta-scrape

provider:
  name: aws
  runtime: nodejs10.x
functions:
  scrape:
    handler: handler.scrape
    description: A basic function for scraping a site's meta tags to populate preview components
    memorySize: 128
    timeout: 15
    events:
      - http:
          path: scrape
          method: get
          cors: true
